version: '2.2'

networks:
  basic:

services:

  ca.detran.car-lifes-cicle.com:
    container_name: ca.detran.car-lifes-cicle.com
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.detran.car-lifes-cicle.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/crypto/ca.detran.car-lifes-cicle.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/crypto/priv-key.pem
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}
    ports:
      - 7020:7054
    working_dir: /etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b ${DETRAN_CA_ADMIN_NAME}:${DETRAN_CA_ADMIN_PASSWORD} -d'
    volumes:
      - ../fabric-config/crypto-config/peerOrganizations/detran.car-lifes-cicle.com/ca/:/etc/hyperledger/fabric-ca-server/crypto
      - ../fabric-config/fabric-ca-server-config/detran.car-lifes-cicle.com/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    networks:
      - basic

  cli.detran.car-lifes-cicle.com:
    container_name: cli.detran.car-lifes-cicle.com
    image: hyperledger/fabric-tools:${FABRIC_VERSION}
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}
      - CORE_PEER_ID=cli.detran.car-lifes-cicle.com
      - CORE_CHAINCODE_KEEPALIVE=10
      #
      - CORE_PEER_LOCALMSPID=detranMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/cli/crypto/users/Admin@detran.car-lifes-cicle.com/msp
      - CORE_PEER_ADDRESS=peer0.detran.car-lifes-cicle.com:7021
    working_dir: /var/hyperledger/cli/
    command: /bin/bash
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../fabric-docker/scripts/cli:/var/hyperledger/cli/scripts/
      - ../fabric-config/config:/var/hyperledger/cli/config/ # genesis.block and channel.tx's
      - ../fabric-config/crypto-config/peerOrganizations/detran.car-lifes-cicle.com:/var/hyperledger/cli/crypto/
      - ../fabric-config/chaincode-packages:/var/hyperledger/cli/chaincode-packages/
      - "$CHAINCODES_BASE_DIR/./chaincodes/car-chaincode/:/var/hyperledger/cli/car/"
      - "$CHAINCODES_BASE_DIR/./chaincodes/person-chaincode/:/var/hyperledger/cli/person/"
    networks:
      - basic

  fablo-rest.detran.car-lifes-cicle.com:
    container_name: fablo-rest.detran.car-lifes-cicle.com
    image: softwaremill/fablo-rest:${FABLO_REST_VERSION}
    environment:
      - PORT=8000
      - MSP_ID=detranMSP
      - FABRIC_CA_URL=http://ca.detran.car-lifes-cicle.com:7054
      - FABRIC_CA_NAME=ca.detran.car-lifes-cicle.com
      - AS_LOCALHOST=false
      - DISCOVERY_URLS=grpc://peer0.detran.car-lifes-cicle.com:7021,grpc://peer1.detran.car-lifes-cicle.com:7022,grpc://peer0.montadora.car-lifes-cicle.com:7041,grpc://peer1.montadora.car-lifes-cicle.com:7042
      - HFC_LOGGING={"error":"console","warn":"console","info":"console"}
    ports:
      - 8800:8000
    networks:
      - basic

  orderer0.orderers-group.detran.car-lifes-cicle.com:
    container_name: orderer0.orderers-group.detran.car-lifes-cicle.com
    image: hyperledger/fabric-orderer:${FABRIC_VERSION}
    environment:
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7030
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/config/Orderers-groupGenesis.block
      - ORDERER_GENERAL_LOCALMSPID=detranMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - GODEBUG=netdns=go
    working_dir: /var/hyperledger/orderer
    command: orderer
    ports:
      - 7030:7030
      - 8030:9440
    volumes:
      - ../fabric-config/config/:/var/hyperledger/config
      - ../fabric-config/crypto-config/peerOrganizations/detran.car-lifes-cicle.com/peers/orderer0.orderers-group.detran.car-lifes-cicle.com/msp/:/var/hyperledger/orderer/msp
      - ../fabric-config/crypto-config/peerOrganizations/detran.car-lifes-cicle.com/peers/orderer0.orderers-group.detran.car-lifes-cicle.com/tls/:/var/hyperledger/orderer/tls
    networks:
      - basic

  peer0.detran.car-lifes-cicle.com:
    container_name: peer0.detran.car-lifes-cicle.com
    image: hyperledger/fabric-peer:${FABRIC_VERSION}
    environment:
      - CORE_PEER_LOCALMSPID=detranMSP
      - CORE_PEER_ID=peer0.detran.car-lifes-cicle.com
      - CORE_PEER_ADDRESS=peer0.detran.car-lifes-cicle.com:7021
      - CORE_PEER_LISTENADDRESS=peer0.detran.car-lifes-cicle.com:7021
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.detran.car-lifes-cicle.com:7021
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.detran.car-lifes-cicle.com:7021
      - CORE_PEER_GOSSIP_BOOTSTRAP="peer0.detran.car-lifes-cicle.com:7021 peer1.detran.car-lifes-cicle.com:7022"
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.detran.car-lifes-cicle.com:7050
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/peer/msp
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:${FABRIC_CCENV_VERSION}
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:${FABRIC_BASEOS_VERSION}
      - CORE_CHAINCODE_JAVA_RUNTIME=hyperledger/fabric-javaenv:${FABRIC_JAVAENV_VERSION}
      #
      - CORE_CHAINCODE_LOGGING_LEVEL=${LOGGING_LEVEL}
      - CORE_CHAINCODE_LOGGING_SHIM=${LOGGING_LEVEL}
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}
      # metrics
      - CORE_OPERATIONS_LISTENADDRESS=peer0.detran.car-lifes-cicle.com:9440
      - CORE_METRICS_PROVIDER=prometheus
      #
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - GODEBUG=netdns=go
    working_dir: /etc/hyperledger/fabric/peer/
    command: peer node start
    ports:
      - 8021:9440
      - 7021:7021
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../fabric-config/crypto-config/peerOrganizations/detran.car-lifes-cicle.com/peers/peer0.detran.car-lifes-cicle.com/msp:/etc/hyperledger/fabric/peer/msp
      - ../fabric-config/crypto-config/peerOrganizations/detran.car-lifes-cicle.com/peers/peer0.detran.car-lifes-cicle.com/tls:/etc/hyperledger/fabric/peer/tls
      - ../fabric-config/crypto-config/peerOrganizations/detran.car-lifes-cicle.com/users:/etc/hyperledger/fabric/peer/msp/users
      - ../fabric-config/config:/etc/hyperledger/fabric/config
    networks:
      - basic

  peer1.detran.car-lifes-cicle.com:
    container_name: peer1.detran.car-lifes-cicle.com
    image: hyperledger/fabric-peer:${FABRIC_VERSION}
    environment:
      - CORE_PEER_LOCALMSPID=detranMSP
      - CORE_PEER_ID=peer1.detran.car-lifes-cicle.com
      - CORE_PEER_ADDRESS=peer1.detran.car-lifes-cicle.com:7022
      - CORE_PEER_LISTENADDRESS=peer1.detran.car-lifes-cicle.com:7022
      - CORE_PEER_GOSSIP_ENDPOINT=peer1.detran.car-lifes-cicle.com:7022
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.detran.car-lifes-cicle.com:7022
      - CORE_PEER_GOSSIP_BOOTSTRAP="peer0.detran.car-lifes-cicle.com:7021 peer1.detran.car-lifes-cicle.com:7022"
      - CORE_PEER_CHAINCODELISTENADDRESS=peer1.detran.car-lifes-cicle.com:7050
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/peer/msp
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:${FABRIC_CCENV_VERSION}
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:${FABRIC_BASEOS_VERSION}
      - CORE_CHAINCODE_JAVA_RUNTIME=hyperledger/fabric-javaenv:${FABRIC_JAVAENV_VERSION}
      #
      - CORE_CHAINCODE_LOGGING_LEVEL=${LOGGING_LEVEL}
      - CORE_CHAINCODE_LOGGING_SHIM=${LOGGING_LEVEL}
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}
      # metrics
      - CORE_OPERATIONS_LISTENADDRESS=peer1.detran.car-lifes-cicle.com:9440
      - CORE_METRICS_PROVIDER=prometheus
      #
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - GODEBUG=netdns=go
    working_dir: /etc/hyperledger/fabric/peer/
    command: peer node start
    ports:
      - 8022:9440
      - 7022:7022
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../fabric-config/crypto-config/peerOrganizations/detran.car-lifes-cicle.com/peers/peer1.detran.car-lifes-cicle.com/msp:/etc/hyperledger/fabric/peer/msp
      - ../fabric-config/crypto-config/peerOrganizations/detran.car-lifes-cicle.com/peers/peer1.detran.car-lifes-cicle.com/tls:/etc/hyperledger/fabric/peer/tls
      - ../fabric-config/crypto-config/peerOrganizations/detran.car-lifes-cicle.com/users:/etc/hyperledger/fabric/peer/msp/users
      - ../fabric-config/config:/etc/hyperledger/fabric/config
    networks:
      - basic

  ca.montadora.car-lifes-cicle.com:
    container_name: ca.montadora.car-lifes-cicle.com
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.montadora.car-lifes-cicle.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/crypto/ca.montadora.car-lifes-cicle.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/crypto/priv-key.pem
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}
    ports:
      - 7040:7054
    working_dir: /etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b ${MONTADORA_CA_ADMIN_NAME}:${MONTADORA_CA_ADMIN_PASSWORD} -d'
    volumes:
      - ../fabric-config/crypto-config/peerOrganizations/montadora.car-lifes-cicle.com/ca/:/etc/hyperledger/fabric-ca-server/crypto
      - ../fabric-config/fabric-ca-server-config/montadora.car-lifes-cicle.com/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    networks:
      - basic

  cli.montadora.car-lifes-cicle.com:
    container_name: cli.montadora.car-lifes-cicle.com
    image: hyperledger/fabric-tools:${FABRIC_VERSION}
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}
      - CORE_PEER_ID=cli.montadora.car-lifes-cicle.com
      - CORE_CHAINCODE_KEEPALIVE=10
      #
      - CORE_PEER_LOCALMSPID=montadoraMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/cli/crypto/users/Admin@montadora.car-lifes-cicle.com/msp
      - CORE_PEER_ADDRESS=peer0.montadora.car-lifes-cicle.com:7041
    working_dir: /var/hyperledger/cli/
    command: /bin/bash
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../fabric-docker/scripts/cli:/var/hyperledger/cli/scripts/
      - ../fabric-config/config:/var/hyperledger/cli/config/ # genesis.block and channel.tx's
      - ../fabric-config/crypto-config/peerOrganizations/montadora.car-lifes-cicle.com:/var/hyperledger/cli/crypto/
      - ../fabric-config/chaincode-packages:/var/hyperledger/cli/chaincode-packages/
      - "$CHAINCODES_BASE_DIR/./chaincodes/car-chaincode/:/var/hyperledger/cli/car/"
      - "$CHAINCODES_BASE_DIR/./chaincodes/person-chaincode/:/var/hyperledger/cli/person/"
    networks:
      - basic

  fablo-rest.montadora.car-lifes-cicle.com:
    container_name: fablo-rest.montadora.car-lifes-cicle.com
    image: softwaremill/fablo-rest:${FABLO_REST_VERSION}
    environment:
      - PORT=8000
      - MSP_ID=montadoraMSP
      - FABRIC_CA_URL=http://ca.montadora.car-lifes-cicle.com:7054
      - FABRIC_CA_NAME=ca.montadora.car-lifes-cicle.com
      - AS_LOCALHOST=false
      - DISCOVERY_URLS=grpc://peer0.detran.car-lifes-cicle.com:7021,grpc://peer1.detran.car-lifes-cicle.com:7022,grpc://peer0.montadora.car-lifes-cicle.com:7041,grpc://peer1.montadora.car-lifes-cicle.com:7042
      - HFC_LOGGING={"error":"console","warn":"console","info":"console"}
    ports:
      - 8801:8000
    networks:
      - basic

  peer0.montadora.car-lifes-cicle.com:
    container_name: peer0.montadora.car-lifes-cicle.com
    image: hyperledger/fabric-peer:${FABRIC_VERSION}
    environment:
      - CORE_PEER_LOCALMSPID=montadoraMSP
      - CORE_PEER_ID=peer0.montadora.car-lifes-cicle.com
      - CORE_PEER_ADDRESS=peer0.montadora.car-lifes-cicle.com:7041
      - CORE_PEER_LISTENADDRESS=peer0.montadora.car-lifes-cicle.com:7041
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.montadora.car-lifes-cicle.com:7041
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.montadora.car-lifes-cicle.com:7041
      - CORE_PEER_GOSSIP_BOOTSTRAP="peer0.montadora.car-lifes-cicle.com:7041 peer1.montadora.car-lifes-cicle.com:7042"
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.montadora.car-lifes-cicle.com:7050
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/peer/msp
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:${FABRIC_CCENV_VERSION}
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:${FABRIC_BASEOS_VERSION}
      - CORE_CHAINCODE_JAVA_RUNTIME=hyperledger/fabric-javaenv:${FABRIC_JAVAENV_VERSION}
      #
      - CORE_CHAINCODE_LOGGING_LEVEL=${LOGGING_LEVEL}
      - CORE_CHAINCODE_LOGGING_SHIM=${LOGGING_LEVEL}
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}
      # metrics
      - CORE_OPERATIONS_LISTENADDRESS=peer0.montadora.car-lifes-cicle.com:9440
      - CORE_METRICS_PROVIDER=prometheus
      #
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - GODEBUG=netdns=go
    working_dir: /etc/hyperledger/fabric/peer/
    command: peer node start
    ports:
      - 8041:9440
      - 7041:7041
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../fabric-config/crypto-config/peerOrganizations/montadora.car-lifes-cicle.com/peers/peer0.montadora.car-lifes-cicle.com/msp:/etc/hyperledger/fabric/peer/msp
      - ../fabric-config/crypto-config/peerOrganizations/montadora.car-lifes-cicle.com/peers/peer0.montadora.car-lifes-cicle.com/tls:/etc/hyperledger/fabric/peer/tls
      - ../fabric-config/crypto-config/peerOrganizations/montadora.car-lifes-cicle.com/users:/etc/hyperledger/fabric/peer/msp/users
      - ../fabric-config/config:/etc/hyperledger/fabric/config
    networks:
      - basic

  peer1.montadora.car-lifes-cicle.com:
    container_name: peer1.montadora.car-lifes-cicle.com
    image: hyperledger/fabric-peer:${FABRIC_VERSION}
    environment:
      - CORE_PEER_LOCALMSPID=montadoraMSP
      - CORE_PEER_ID=peer1.montadora.car-lifes-cicle.com
      - CORE_PEER_ADDRESS=peer1.montadora.car-lifes-cicle.com:7042
      - CORE_PEER_LISTENADDRESS=peer1.montadora.car-lifes-cicle.com:7042
      - CORE_PEER_GOSSIP_ENDPOINT=peer1.montadora.car-lifes-cicle.com:7042
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.montadora.car-lifes-cicle.com:7042
      - CORE_PEER_GOSSIP_BOOTSTRAP="peer0.montadora.car-lifes-cicle.com:7041 peer1.montadora.car-lifes-cicle.com:7042"
      - CORE_PEER_CHAINCODELISTENADDRESS=peer1.montadora.car-lifes-cicle.com:7050
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/peer/msp
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:${FABRIC_CCENV_VERSION}
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:${FABRIC_BASEOS_VERSION}
      - CORE_CHAINCODE_JAVA_RUNTIME=hyperledger/fabric-javaenv:${FABRIC_JAVAENV_VERSION}
      #
      - CORE_CHAINCODE_LOGGING_LEVEL=${LOGGING_LEVEL}
      - CORE_CHAINCODE_LOGGING_SHIM=${LOGGING_LEVEL}
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}
      # metrics
      - CORE_OPERATIONS_LISTENADDRESS=peer1.montadora.car-lifes-cicle.com:9440
      - CORE_METRICS_PROVIDER=prometheus
      #
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - GODEBUG=netdns=go
    working_dir: /etc/hyperledger/fabric/peer/
    command: peer node start
    ports:
      - 8042:9440
      - 7042:7042
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../fabric-config/crypto-config/peerOrganizations/montadora.car-lifes-cicle.com/peers/peer1.montadora.car-lifes-cicle.com/msp:/etc/hyperledger/fabric/peer/msp
      - ../fabric-config/crypto-config/peerOrganizations/montadora.car-lifes-cicle.com/peers/peer1.montadora.car-lifes-cicle.com/tls:/etc/hyperledger/fabric/peer/tls
      - ../fabric-config/crypto-config/peerOrganizations/montadora.car-lifes-cicle.com/users:/etc/hyperledger/fabric/peer/msp/users
      - ../fabric-config/config:/etc/hyperledger/fabric/config
    networks:
      - basic

  db.explorer.example.com:
    image: hyperledger/explorer-db:${HYPERLEDGER_EXPLORER_VERSION}
    container_name: db.explorer.example.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 5s
      timeout: 10s
      retries: 7
    volumes:
      - /var/lib/postgresql/data
    networks:
      - basic

  explorer.example.com:
    image: hyperledger/explorer:${HYPERLEDGER_EXPLORER_VERSION}
    restart: on-failure:8
    container_name: explorer.example.com
    environment:
      - DATABASE_HOST=db.explorer.example.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ../fabric-config/explorer/config-global.json:/opt/explorer/app/platform/fabric/config.json
      - ../fabric-config/explorer:/opt/explorer/app/platform/fabric/connection-profile
      - ../fabric-config/crypto-config:/tmp/crypto
    ports:
      - "7010:8080"
    depends_on:
      db.explorer.example.com:
        condition: service_healthy
    networks:
      - basic
